services:
  postgres:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d api"]
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    
    
  api:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/testdb
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "/opt/wait-for-it.sh postgres:5432 -- pnpm start:prod"
    mem_limit: 512m