version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    

  api:
    build:
      context: .
      dockerfile: e2e.Dockerfile
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/testdb
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run test:e2e
    mem_limit: 512m

volumes:
  pgdata:
    driver: local
