name: NestJS API CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Start services (Postgres, API)
        run: |
          docker compose -f docker-compose.ci.yaml --env-file env-example -p ci up -d postgres api
      
      # Add proper health checks for services
      - name: Wait for services to be ready
        run: |
          # Wait for postgres
          docker compose -p ci exec -T postgres sh -c 'until pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}; do sleep 2; done'
          
          # Wait for API with increased timeout and proper docker network usage
          docker compose -p ci exec -T api sh -c 'until curl -s http://localhost:${APP_PORT}/api; do sleep 5; echo "Waiting for API..."; done'
      
      - name: Run E2E tests
        run: |
          docker compose -p ci exec -T api pnpm test:e2e -- --runInBand

      # Add cleanup step
      - name: Cleanup
        if: always()
        run: |
          docker compose -p ci down -v