name: Docker E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Environment File
        run: |
          echo "DATABASE_PORT=5432" >> .env
          echo "DATABASE_USERNAME=postgres" >> .env
          echo "DATABASE_PASSWORD=postgres" >> .env
          echo "DATABASE_NAME=testdb" >> .env
          echo "DATABASE_HOST=localhost" >> .env
          echo "APP_PORT=3000" >> .env
          echo "NODE_ENV=test" >> .env
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/testdb" >> .env

      - name: Start Docker Services
        run: |
          docker compose -f docker-compose.yml --env-file .env up -d

      - name: Wait for PostgreSQL to be Ready
        run: |
          until docker compose exec -T postgres pg_isready -U postgres -d testdb; do
            echo "Waiting for PostgreSQL...";
            sleep 2;
          done
          echo "PostgreSQL is ready!"

      - name: Run End-to-End Tests
        run: docker compose exec -T api npm run test:e2e

      - name: Stop Docker Services
        if: always()
        run: docker compose down
