name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Services
        run: |
          docker compose -f docker-compose.ci.yaml up -d

      - name: Wait for PostgreSQL to be Ready
        run: |
          echo "Waiting for PostgreSQL to become healthy..."
          until docker compose exec -T postgres pg_isready -U postgres -d testdb; do
            sleep 2;
          done
          echo "PostgreSQL is ready!"

      - name: Run End-to-End Tests
        run: docker compose exec -T api npm run test:e2e

      - name: Stop Docker Services
        if: always()
        run: docker compose -f docker-compose.ci.yaml down
