name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env File
        run: |
          echo "DATABASE_PORT=5432" >> $GITHUB_WORKSPACE/.env
          echo "DATABASE_USERNAME=postgres" >> $GITHUB_WORKSPACE/.env
          echo "DATABASE_PASSWORD=postgres" >> $GITHUB_WORKSPACE/.env
          echo "DATABASE_NAME=testdb" >> $GITHUB_WORKSPACE/.env
          echo "DATABASE_HOST=postgres" >> $GITHUB_WORKSPACE/.env
          echo "APP_PORT=3000" >> $GITHUB_WORKSPACE/.env
          echo "NODE_ENV=test" >> $GITHUB_WORKSPACE/.env
          echo "DATABASE_URL=postgres://postgres:postgres@postgres:5432/testdb" >> $GITHUB_WORKSPACE/.env
          cat $GITHUB_WORKSPACE/.env  # Debugging: Ensure .env is created

      - name: Start Docker Services
        run: docker compose -f docker-compose.ci.yaml up -d

      - name: Wait for API to be Ready
        run: |
          echo "Waiting for API to be ready..."
          until curl -s http://127.0.0.1:3000 > /dev/null; do
            echo "API is not ready yet... retrying in 5 seconds";
            sleep 5;
          done
          echo "API is ready!"

      - name: Debug API Logs (if API is not reachable)
        if: failure()
        run: docker compose logs api

      - name: Run Database Migrations and Seeders
        run: |
          docker compose exec -T api npm run db:migrate:deploy
          docker compose exec -T api npm run db:seed

      - name: Run End-to-End Tests
        run: docker compose exec -T api npm run test:e2e

      - name: Stop Docker Services
        if: always()
        run: docker compose -f docker-compose.ci.yaml down
