name: CoreAPI E2E Tests

on:
  pull_request:
    branches:
      - staging

jobs:
  e2e_tests:
    runs-on: ubuntu-22.04
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://test:secret@postgres:5432/api

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose
        run: |
          docker-compose -f docker-compose.ci.yml up -d --build
          docker-compose -f docker-compose.ci.yml logs api --follow &

      - name: Wait for Postgres to be ready
        run: |
          docker-compose -f docker-compose.ci.yml exec -T postgres sh -c 'until pg_isready -U test -d api; do sleep 1; done'

      - name: Wait for API service to be ready
        run: |
          docker-compose -f docker-compose.ci.yml exec -T api sh -c "while ! curl -s http://localhost:3000 > /dev/null; do sleep 1; done"

      - name: Run tests
        run: |
          docker-compose -f docker-compose.ci.yml exec -T api npm run test:e2e

      - name: Cleanup
        if: always()
        run: docker-compose -f docker-compose.ci.yml down -v